var mongoose = require("mongoose");

var videoSchema = mongoose.Schema({
	user       : {type: mongoose.Schema.Types.ObjectId, ref:"User"},
	name       : String,
	path       : String,
	uploadedOn : {type: Date, default:Date.now},
	likes      : [String], //stores userId(id generated by mongoDb) in string format
	public     : {type: String, default: "Yes", enum:["Yes", "No"]},
	thumbs     : String,
	comments   : [
					{
						
						data        : String,
						commentedBy : {type: mongoose.Schema.Types.ObjectId, ref:"User"},
						commentedOn : {type: Date, default:Date.now}

					}
				 ]
});


module.exports = mongoose.model("Video", videoSchema);